# Default values for diktyo-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: diktyo-scheduler
  image: jpedro1992/kube-scheduler:v1.1
  replicaCount: 1
  leaderElect: false
  weight: 5 # Attribute a weight to the scoring plugin.

controller:
  name: scheduler-plugins-controller
  image: jpedro1992/controller:kubecon
  replicaCount: 1

plugins:
  namespaces: ["default"]
  weightsName: "UserDefined" # Define here the costs you intend to use
  networkTopologyName: "nt-cluster" # Define here the name of the NetworkTopology CR

diktyoConfig:
  name: diktyo-config
  mountPath: /etc/diktyo

KubeConfig:
  name: "diktyo-scheduler-kubeconfig"
  mountPath: /etc/diktyo-scheduler-kubeconfig

