# Default values for diktyo-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: diktyo-scheduler
  image: registry.k8s.io/scheduler-plugins/kube-scheduler:v0.26.7
  replicaCount: 1
  leaderElect: false
  weight: 5 # Attribute a weight to the scoring plugin.

controller:
  name: scheduler-plugins-controller
  image: registry.k8s.io/scheduler-plugins/controller:v0.26.7
  replicaCount: 1

appGroupController:
  name: appgroup-controller
  image: jpedro1992/appgroup-controller:security
  replicaCount: 1

networkTopologyController:
  name: networktopology-controller
  image: jpedro1992/networktopology-controller:security
  replicaCount: 1

plugins:
  namespaces: ["default"]
  weightsName: "NetperfCosts" # Define here the costs you intend to use
  networkTopologyName: "nt-cluster" # Define here the name of the NetworkTopology CR

diktyoConfig:
  name: diktyo-config
  mountPath: /etc/diktyo

KubeConfig:
  name: "diktyo-scheduler-kubeconfig"
  mountPath: /etc/diktyo-scheduler-kubeconfig

