---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.diktyoConfig.name }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.diktyoConfig.name }}.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: {{ .Values.scheduler.leaderElect }}
    clientConnection:
      kubeconfig: {{ .Values.KubeConfig.mountPath }}/{{ .Values.KubeConfig.name }}.yaml
    profiles:
      - schedulerName: {{ .Values.scheduler.name }}
        plugins:
          queueSort:
            enabled:
              - name: TopologicalSort
            disabled:
              - name: "*"
          filter:
            enabled:
              - name: NetworkOverhead
          score:
            enabled: # A higher weight is given to NetworkMinCost to favor allocation schemes with lower latency.
              - name: NetworkOverhead
                weight: {{ .Values.scheduler.weight }}
        pluginConfig:
          - name: TopologicalSort
            args:
              kubeConfigPath: {{ .Values.KubeConfig.mountPath }}/{{ .Values.KubeConfig.name }}.yaml
              namespaces:
                {{- range $.Values.plugins.namespaces }}
                - {{ . }}
                {{- end }}
          - name: NetworkOverhead
            args:
              kubeConfigPath: {{ .Values.KubeConfig.mountPath }}/{{ .Values.KubeConfig.name }}.yaml
              namespaces:
                {{- range $.Values.plugins.namespaces }}
                - {{ . }}
                {{- end }}
              weightsName: {{ .Values.plugins.weightsName }}
              networkTopologyName: {{ .Values.plugins.networkTopologyName }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.KubeConfig.name }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.KubeConfig.name }}.yaml: |
    # TODO: Add here your Kubeconfig file!
