apiVersion: appgroup.diktyo.x-k8s.io/v1alpha1
kind: AppGroup
metadata:
  name: online-boutique
spec:
  numMembers: 11
  topologySortingAlgorithm: AlternateKahn
  workloads:
    - workload:
        kind: Deployment
        name: frontend
        selector: frontend
        apiVersion: apps/v1
        namespace: default
      dependencies:
        - workload:
            kind: Deployment
            name: cartservice
            selector: cartservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "50Mi"
          maxNetworkCost: 400
        - workload:
            kind: Deployment
            name: productcatalogservice
            selector: productcatalogservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "70Mi"
          maxNetworkCost: 40
        - workload:
            kind: Deployment
            name: currencyservice
            selector: currencyservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 400
        - workload:
            kind: Deployment
            name: shippingservice
            selector: shippingservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 40
        - workload:
            kind: Deployment
            name: checkoutservice
            selector: checkoutservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 500
        - workload:
            kind: Deployment
            name: adservice
            selector: adservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 400
    - workload:
        kind: Deployment
        name: cartservice
        selector: cartservice
        apiVersion: apps/v1
        namespace: default
      dependencies:
        - workload:
            kind: Deployment
            name: frontend
            selector: frontend
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "10Mi"
          maxNetworkCost: 400
        - workload:
            kind: Deployment
            name: redis-cart
            selector: redis-cart
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 400
    - workload:
        kind: Deployment
        name: productcatalogservice
        selector: productcatalogservice
        apiVersion: apps/v1
        namespace: default
      dependencies:
        - workload:
            kind: Deployment
            name: frontend
            selector: frontend
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 50
        - workload:
            kind: Deployment
            name: checkoutservice
            selector: checkoutservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "10Mi"
          maxNetworkCost: 400
        - workload:
            kind: Deployment
            name: recommendationservice
            selector: recommendationservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 400
    - workload:
        kind: Deployment
        name: currencyservice
        selector: currencyservice
        apiVersion: apps/v1
        namespace: default
      dependencies:
        - workload:
            kind: Deployment
            name: frontend
            selector: frontend
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 100
        - workload:
            kind: Deployment
            name: checkoutservice
            selector: checkoutservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 400
    - workload:
        kind: Deployment
        name: paymentservice
        selector: paymentservice
        apiVersion: apps/v1
        namespace: default
      dependencies:
        - workload:
            kind: Deployment
            name: checkoutservice
            selector: checkoutservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "15Mi"
          maxNetworkCost: 400
    - workload:
        kind: Deployment
        name: shippingservice
        selector: shippingservice
        apiVersion: apps/v1
        namespace: default
      dependencies:
        - workload:
            kind: Deployment
            name: frontend
            selector: frontend
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 400
        - workload:
            kind: Deployment
            name: checkoutservice
            selector: checkoutservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "10Mi"
          maxNetworkCost: 400
    - workload:
        kind: Deployment
        name: emailservice
        selector: emailservice
        apiVersion: apps/v1
        namespace: default
      dependencies:
        - workload:
            kind: Deployment
            name: checkoutservice
            selector: checkoutservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 100
    - workload:
        kind: Deployment
        name: checkoutservice
        selector: checkoutservice
        apiVersion: apps/v1
        namespace: default
      dependencies:
        - workload:
            kind: Deployment
            name: frontend
            selector: frontend
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 400
        - workload:
            kind: Deployment
            name: cartservice
            selector: cartservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 30
        - workload:
            kind: Deployment
            name: productcatalogservice
            selector: productcatalogservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "200Mi"
          maxNetworkCost: 20
        - workload:
            kind: Deployment
            name: currencyservice
            selector: currencyservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "15Mi"
          maxNetworkCost: 400
        - workload:
            kind: Deployment
            name: paymentservice
            selector: paymentservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 400
        - workload:
            kind: Deployment
            name: shippingservice
            selector: shippingservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 400
        - workload:
            kind: Deployment
            name: emailservice
            selector: emailservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 400
    - workload:
        kind: Deployment
        name: recommendationservice
        selector: recommendationservice
        apiVersion: apps/v1
        namespace: default
      dependencies:
        - workload:
            kind: Deployment
            name: frontend
            selector: frontend
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 300
        - workload:
            kind: Deployment
            name: productcatalogservice
            selector: productcatalogservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 400
    - workload:
        kind: Deployment
        name: adservice
        selector: adservice
        apiVersion: apps/v1
        namespace: default
      dependencies:
        - workload:
            kind: Deployment
            name: frontend
            selector: frontend
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 200
    - workload:
        kind: Deployment
        name: redis-cart
        selector: redis-cart
        apiVersion: apps/v1
        namespace: default
      dependencies:
        - workload:
            kind: Deployment
            name: cartservice
            selector: cartservice
            apiVersion: apps/v1
            namespace: default
          minBandwidth: "100Mi"
          maxNetworkCost: 400
---

